-- =====================================================================
--  FANTASY · Balance global de precios (equipos ya existentes en la DB)
--  Aplica la curva de reprice.mjs (techo ~21M, piso 4.5) sobre el precio
--  actual de cada jugador, preservando el orden por mérito. Objetivo: que no
--  se pueda armar un plantel "todas estrellas" (máx ~3 cracks ≥15M en un XI).
--
--  Solo toca los 35 equipos que YA estaban cargados; los 13 de
--  migracion-fantasy-squads.sql ya salen balanceados de esa migración.
--  Idempotente (valores absolutos): re-correrlo no acumula.
--  Pegar en Supabase → SQL Editor → Run.
-- =====================================================================

begin;

update public.fantasy_players set price = 4.5 where
  (team = 'Algeria' and name = 'H. Aouar')
  or (team = 'Algeria' and name = 'N. Bentaleb')
  or (team = 'Algeria' and name = 'H. Boudaoui')
  or (team = 'Algeria' and name = 'I. Maza')
  or (team = 'Algeria' and name = 'Y. Titraoui')
  or (team = 'Algeria' and name = 'R. Zerrouki')
  or (team = 'Algeria' and name = 'F. Chaïbi')
  or (team = 'Argentina' and name = 'V. Barco')
  or (team = 'Argentina' and name = 'G. Lo Celso')
  or (team = 'Argentina' and name = 'E. Palacios')
  or (team = 'Argentina' and name = 'L. Paredes')
  or (team = 'Argentina' and name = 'N. González')
  or (team = 'Argentina' and name = 'R. De Paul')
  or (team = 'Australia' and name = 'J. Irvine')
  or (team = 'Australia' and name = 'C. Devlin')
  or (team = 'Australia' and name = 'A. O Neill')
  or (team = 'Australia' and name = 'Paul Okon-Engstler')
  or (team = 'Australia' and name = 'C. Metcalfe')
  or (team = 'Australia' and name = 'A. Hrustic')
  or (team = 'Australia' and name = 'M. Leckie')
  or (team = 'Australia' and name = 'A. Mabil')
  or (team = 'Austria' and name = 'C. Baumgartner')
  or (team = 'Austria' and name = 'C. Chukwuemeka')
  or (team = 'Austria' and name = 'F. Grillitsch')
  or (team = 'Austria' and name = 'M. Sabitzer')
  or (team = 'Austria' and name = 'X. Schlager')
  or (team = 'Austria' and name = 'R. Schmid')
  or (team = 'Austria' and name = 'A. Schöpf')
  or (team = 'Austria' and name = 'N. Seiwald')
  or (team = 'Austria' and name = 'P. Wanner')
  or (team = 'Austria' and name = 'P. Wimmer')
  or (team = 'Austria' and name = 'M. Gregoritsch')
  or (team = 'Brazil' and name = 'Bruno Guimarães')
  or (team = 'Brazil' and name = 'Casemiro')
  or (team = 'Brazil' and name = 'Fabinho')
  or (team = 'Brazil' and name = 'Lucas Paquetá')
  or (team = 'Brazil' and name = 'Danilo Santos')
  or (team = 'Brazil' and name = 'Luiz Henrique')
  or (team = 'Brazil' and name = 'Raphinha')
  or (team = 'Canada' and name = 'N. Sigur')
  or (team = 'Canada' and name = 'J. Shaffelburg')
  or (team = 'Canada' and name = 'L. Millar')
  or (team = 'Canada' and name = 'M. Choinière')
  or (team = 'Canada' and name = 'S. Eustáquio')
  or (team = 'Canada' and name = 'I. Koné')
  or (team = 'Canada' and name = 'J. Osorio')
  or (team = 'Canada' and name = 'N. Saliba')
  or (team = 'Canada' and name = 'M. Flores')
  or (team = 'Canada' and name = 'T. Buchanan')
  or (team = 'Canada' and name = 'A. Ahmed')
  or (team = 'Cape Verde Islands' and name = 'Telmo Arcanjo')
  or (team = 'Cape Verde Islands' and name = 'Deroy Duarte')
  or (team = 'Cape Verde Islands' and name = 'L. Duarte')
  or (team = 'Cape Verde Islands' and name = 'João Paulo')
  or (team = 'Cape Verde Islands' and name = 'Kevin Pina')
  or (team = 'Cape Verde Islands' and name = 'Jamiro Monteiro')
  or (team = 'Cape Verde Islands' and name = 'Yannick Semedo')
  or (team = 'Cape Verde Islands' and name = 'Garry Rodrigues')
  or (team = 'Cape Verde Islands' and name = 'Willy Semedo')
  or (team = 'Cape Verde Islands' and name = 'Hélio Varela')
  or (team = 'Cape Verde Islands' and name = 'Ryan Mendes')
  or (team = 'Congo DR' and name = 'E. Kayembe')
  or (team = 'Congo DR' and name = 'S. Moutoussamy')
  or (team = 'Congo DR' and name = 'N. Mukau')
  or (team = 'Congo DR' and name = 'C. Pickel')
  or (team = 'Congo DR' and name = 'N. Sadiki')
  or (team = 'Congo DR' and name = 'A. Tshibola')
  or (team = 'Congo DR' and name = 'N. Mbuku')
  or (team = 'Congo DR' and name = 'T. Bongonda')
  or (team = 'Croatia' and name = 'J. Stanisic')
  or (team = 'Croatia' and name = 'T. Fruk')
  or (team = 'Croatia' and name = 'K. Jakic')
  or (team = 'Croatia' and name = 'M. Kovacic')
  or (team = 'Croatia' and name = 'L. Modric')
  or (team = 'Croatia' and name = 'N. Moro')
  or (team = 'Croatia' and name = 'M. Pasalic')
  or (team = 'Croatia' and name = 'L. Sucic')
  or (team = 'Croatia' and name = 'N. Vlasic')
  or (team = 'Croatia' and name = 'I. Perisic')
  or (team = 'Ecuador' and name = 'J. Alcívar')
  or (team = 'Ecuador' and name = 'M. Caicedo')
  or (team = 'Ecuador' and name = 'D. Castillo')
  or (team = 'Ecuador' and name = 'A. Franco')
  or (team = 'Ecuador' and name = 'K. Páez')
  or (team = 'Ecuador' and name = 'A. Minda')
  or (team = 'Ecuador' and name = 'A. Valencia')
  or (team = 'Ecuador' and name = 'P. Vite')
  or (team = 'Ecuador' and name = 'J. Yeboah')
  or (team = 'Ecuador' and name = 'N. Angulo')
  or (team = 'England' and name = 'E. Anderson')
  or (team = 'England' and name = 'E. Eze')
  or (team = 'England' and name = 'J. Henderson')
  or (team = 'England' and name = 'K. Mainoo')
  or (team = 'England' and name = 'M. Rogers')
  or (team = 'Germany' and name = 'N. Amiri')
  or (team = 'Germany' and name = 'L. Goretzka')
  or (team = 'Germany' and name = 'P. Groß')
  or (team = 'Germany' and name = 'L. Karl')
  or (team = 'Germany' and name = 'F. Nmecha')
  or (team = 'Germany' and name = 'A. Pavlovic')
  or (team = 'Germany' and name = 'A. Stiller')
  or (team = 'Ghana' and name = 'E. Owusu')
  or (team = 'Ghana' and name = 'T. Partey')
  or (team = 'Ghana' and name = 'K. Sibo')
  or (team = 'Ghana' and name = 'Caleb Marfo Yirenkyi')
  or (team = 'Ghana' and name = 'A. Boakye')
  or (team = 'Ghana' and name = 'A. Fatawu')
  or (team = 'Ghana' and name = 'P. Adu')
  or (team = 'Haiti' and name = 'J. Bellegarde')
  or (team = 'Haiti' and name = 'D. Jean-Jacques')
  or (team = 'Haiti' and name = 'L. Pierre')
  or (team = 'Haiti' and name = 'W. Pierre')
  or (team = 'Haiti' and name = 'C. F. Sainte')
  or (team = 'Haiti' and name = 'D. Simon')
  or (team = 'Haiti' and name = 'J. Casimir')
  or (team = 'Haiti' and name = 'R. Providence')
  or (team = 'Iraq' and name = 'Amir Al Ammari')
  or (team = 'Iraq' and name = 'Ibraheem Bayesh')
  or (team = 'Iraq' and name = 'Zidane Iqbal')
  or (team = 'Iraq' and name = 'Z. Ismaeel')
  or (team = 'Iraq' and name = 'A. Sher')
  or (team = 'Iraq' and name = 'Kevin Yakob')
  or (team = 'Iraq' and name = 'M. Farji')
  or (team = 'Ivory Coast' and name = 'S. Fofana')
  or (team = 'Ivory Coast' and name = 'C. Inao Oulai')
  or (team = 'Ivory Coast' and name = 'F. Kessié')
  or (team = 'Ivory Coast' and name = 'I. Sangaré')
  or (team = 'Ivory Coast' and name = 'J. Seri')
  or (team = 'Ivory Coast' and name = 'P. Guiagon')
  or (team = 'Ivory Coast' and name = 'O. Diakité')
  or (team = 'Ivory Coast' and name = 'Y. Diomande')
  or (team = 'Japan' and name = 'R. Doan')
  or (team = 'Japan' and name = 'W. Endo')
  or (team = 'Japan' and name = 'D. Kamada')
  or (team = 'Japan' and name = 'K. Sano')
  or (team = 'Japan' and name = 'A. Tanaka')
  or (team = 'Japan' and name = 'Keito Nakamura')
  or (team = 'Japan' and name = 'Y. Suzuki')
  or (team = 'Jordan' and name = 'M. Al Daoud')
  or (team = 'Jordan' and name = 'Ibrahim Sa''deh')
  or (team = 'Jordan' and name = 'Nizar Al Rashdan')
  or (team = 'Jordan' and name = 'Noor Al Rawabdeh')
  or (team = 'Jordan' and name = 'Rajaei Ayed')
  or (team = 'Jordan' and name = 'Amer Jamous')
  or (team = 'Jordan' and name = 'Mahmoud Al Mardi')
  or (team = 'Mexico' and name = 'O. Vargas')
  or (team = 'Mexico' and name = 'L. Chávez')
  or (team = 'Mexico' and name = 'Álvaro Fidalgo')
  or (team = 'Mexico' and name = 'B. Gutiérrez')
  or (team = 'Mexico' and name = 'É. Lira')
  or (team = 'Mexico' and name = 'G. Mora')
  or (team = 'Mexico' and name = 'O. Pineda')
  or (team = 'Mexico' and name = 'L. Romo')
  or (team = 'Mexico' and name = 'R. Alvarado')
  or (team = 'Mexico' and name = 'C. Huerta')
  or (team = 'Mexico' and name = 'J. Quiñones')
  or (team = 'Morocco' and name = 'S. Amrabat')
  or (team = 'Morocco' and name = 'A. Bouaddi')
  or (team = 'Morocco' and name = 'N. El Aynaoui')
  or (team = 'Morocco' and name = 'B. El Khannouss')
  or (team = 'Morocco' and name = 'S. El Mourabet')
  or (team = 'Morocco' and name = 'A. Ounahi')
  or (team = 'Morocco' and name = 'C. Talbi')
  or (team = 'Morocco' and name = 'Brahim Díaz')
  or (team = 'Morocco' and name = 'A. Amaimouni')
  or (team = 'Morocco' and name = 'A. Ezzalzouli')
  or (team = 'Netherlands' and name = 'R. Gravenberch')
  or (team = 'Netherlands' and name = 'T. Koopmeiners')
  or (team = 'Netherlands' and name = 'T. Reijnders')
  or (team = 'Netherlands' and name = 'G. Til')
  or (team = 'Netherlands' and name = 'Q. Timber')
  or (team = 'Netherlands' and name = 'M. de Roon')
  or (team = 'Norway' and name = 'T. Aasgaard')
  or (team = 'Norway' and name = 'F. Aursnes')
  or (team = 'Norway' and name = 'P. Berg')
  or (team = 'Norway' and name = 'S. Berge')
  or (team = 'Norway' and name = 'Oscar Bobb')
  or (team = 'Norway' and name = 'M. Ødegaard')
  or (team = 'Norway' and name = 'M. Thorsby')
  or (team = 'Norway' and name = 'K. Thorstvedt')
  or (team = 'Norway' and name = 'J. Hauge')
  or (team = 'Norway' and name = 'A. Nusa')
  or (team = 'Panama' and name = 'C. Harvey')
  or (team = 'Panama' and name = 'A. Carrasquilla')
  or (team = 'Panama' and name = 'A. Godoy')
  or (team = 'Panama' and name = 'C. Martinez')
  or (team = 'Panama' and name = 'J. Rodríguez')
  or (team = 'Panama' and name = 'Y. Bárcenas')
  or (team = 'Panama' and name = 'I. Díaz')
  or (team = 'Panama' and name = 'A. Londoño')
  or (team = 'Paraguay' and name = 'D. Bobadilla')
  or (team = 'Paraguay' and name = 'G. Caballero')
  or (team = 'Paraguay' and name = 'A. Cubas')
  or (team = 'Paraguay' and name = 'M. Galarza')
  or (team = 'Paraguay' and name = 'D. Gómez')
  or (team = 'Paraguay' and name = 'Maurício')
  or (team = 'Paraguay' and name = 'B. Ojeda')
  or (team = 'Paraguay' and name = 'R. Sosa')
  or (team = 'Paraguay' and name = 'M. Almirón')
  or (team = 'Portugal' and name = 'João Neves')
  or (team = 'Portugal' and name = 'Rúben Neves')
  or (team = 'Portugal' and name = 'Matheus Nunes')
  or (team = 'Qatar' and name = 'Jassem Gaber')
  or (team = 'Qatar' and name = 'Assim Madibo')
  or (team = 'Qatar' and name = 'Abdulaziz Hatem')
  or (team = 'Qatar' and name = 'Karim Boudiaf')
  or (team = 'Qatar' and name = 'Ahmed Fathi')
  or (team = 'Qatar' and name = 'Mohamed Al Manai')
  or (team = 'Saudi Arabia' and name = 'Mohammed Abu Al Shamat')
  or (team = 'Saudi Arabia' and name = 'Nasser Al Dawsari')
  or (team = 'Saudi Arabia' and name = 'Mohamed Kanno')
  or (team = 'Saudi Arabia' and name = 'Ziyad Al Johani')
  or (team = 'Saudi Arabia' and name = 'Abdullah Al Khaibari')
  or (team = 'Saudi Arabia' and name = 'Ala Al Haji')
  or (team = 'Saudi Arabia' and name = 'Salem Al Dawsari')
  or (team = 'Scotland' and name = 'R. Christie')
  or (team = 'Scotland' and name = 'L. Ferguson')
  or (team = 'Scotland' and name = 'T. Fletcher')
  or (team = 'Scotland' and name = 'J.  McGinn')
  or (team = 'Scotland' and name = 'K. McLean')
  or (team = 'Scotland' and name = 'S. McTominay')
  or (team = 'Scotland' and name = 'B. Doak')
  or (team = 'Scotland' and name = 'Findlay Curtis')
  or (team = 'South Africa' and name = 'J. Adams')
  or (team = 'South Africa' and name = 'T. Mbatha')
  or (team = 'South Africa' and name = 'T. Mokoena')
  or (team = 'South Africa' and name = 'S. Sithole')
  or (team = 'South Africa' and name = 'T. Zwane')
  or (team = 'South Africa' and name = 'T. Moremi')
  or (team = 'South Africa' and name = 'K. Sebelebele')
  or (team = 'South Korea' and name = 'Park Jin-Seop')
  or (team = 'South Korea' and name = 'Lee Tae-Seok')
  or (team = 'South Korea' and name = 'Seol Young-Woo')
  or (team = 'South Korea' and name = 'J. Castrop')
  or (team = 'South Korea' and name = 'Hwang In-Beom')
  or (team = 'South Korea' and name = 'Kim Jin-Gyu')
  or (team = 'South Korea' and name = 'Lee Jae-Sung')
  or (team = 'South Korea' and name = 'Lee Kang-In')
  or (team = 'South Korea' and name = 'Paik Seung-Ho')
  or (team = 'Spain' and name = 'Marcos Llorente')
  or (team = 'Spain' and name = 'Mikel Merino')
  or (team = 'Spain' and name = 'Fabián Ruiz')
  or (team = 'Spain' and name = 'Martín Zubimendi')
  or (team = 'Spain' and name = 'Álex Baena')
  or (team = 'Spain' and name = 'Yeremy Pino')
  or (team = 'Spain' and name = 'Ferran Torres')
  or (team = 'Sweden' and name = 'G. Gudmundsson')
  or (team = 'Sweden' and name = 'H. Johansson')
  or (team = 'Sweden' and name = 'E. Stroud')
  or (team = 'Sweden' and name = 'A. Bernhardsson')
  or (team = 'Sweden' and name = 'Y. Ayari')
  or (team = 'Sweden' and name = 'L. Bergvall')
  or (team = 'Sweden' and name = 'J. Karlström')
  or (team = 'Sweden' and name = 'K. Sema')
  or (team = 'Sweden' and name = 'M. Svanberg')
  or (team = 'Sweden' and name = 'B. Zeneli')
  or (team = 'Sweden' and name = 'T. Ali')
  or (team = 'Switzerland' and name = 'M. Aebischer')
  or (team = 'Switzerland' and name = 'R. Freuler')
  or (team = 'Switzerland' and name = 'A. Jashari')
  or (team = 'Switzerland' and name = 'D. Sow')
  or (team = 'Switzerland' and name = 'G. Xhaka')
  or (team = 'Switzerland' and name = 'C. Fassnacht')
  or (team = 'Switzerland' and name = 'F. Rieder')
  or (team = 'Switzerland' and name = 'D. Ndoye')
  or (team = 'Tunisia' and name = 'M. Ben Ouanes')
  or (team = 'Tunisia' and name = 'Ismaël Gharbi')
  or (team = 'Tunisia' and name = 'R. Khedira')
  or (team = 'Tunisia' and name = 'H. Mejbri')
  or (team = 'Tunisia' and name = 'E. Skhiri')
  or (team = 'Tunisia' and name = 'A. Ben Slimane')
  or (team = 'Tunisia' and name = 'H. Mahmoud')
  or (team = 'Tunisia' and name = 'E. Achouri')
  or (team = 'Turkey' and name = 'H. Çalhanoglu')
  or (team = 'Turkey' and name = 'O. Kokçu')
  or (team = 'Turkey' and name = 'S. Özcan')
  or (team = 'Turkey' and name = 'I. Yüksek')
  or (team = 'Turkey' and name = 'C. Uzun')
  or (team = 'Turkey' and name = 'O. Aydin')
  or (team = 'Turkey' and name = 'A. Güler')
  or (team = 'Turkey' and name = 'Y. Akgün')
  or (team = 'Turkey' and name = 'I. Kahveci');

update public.fantasy_players set price = 5 where
  (team = 'Algeria' and name = 'M. Amoura')
  or (team = 'Algeria' and name = 'A. Benbouali')
  or (team = 'Algeria' and name = 'A. Boulbina')
  or (team = 'Algeria' and name = 'F. Ghedjemis')
  or (team = 'Algeria' and name = 'A. Gouiri')
  or (team = 'Algeria' and name = 'A. Hadj-Moussa')
  or (team = 'Algeria' and name = 'R. Mahrez')
  or (team = 'Argentina' and name = 'T. Almada')
  or (team = 'Argentina' and name = 'N. Paz')
  or (team = 'Argentina' and name = 'J. López')
  or (team = 'Argentina' and name = 'G. Simeone')
  or (team = 'Australia' and name = 'C. Volpato')
  or (team = 'Australia' and name = 'N. Irankunda')
  or (team = 'Australia' and name = 'T. Yengi')
  or (team = 'Australia' and name = 'M. Touré')
  or (team = 'Australia' and name = 'N. Velupillay')
  or (team = 'Austria' and name = 'M. Arnautovic')
  or (team = 'Austria' and name = 'S. Kalajdzic')
  or (team = 'Brazil' and name = 'Matheus Cunha')
  or (team = 'Brazil' and name = 'Endrick')
  or (team = 'Brazil' and name = 'Gabriel Martinelli')
  or (team = 'Brazil' and name = 'Rayan')
  or (team = 'Brazil' and name = 'Thiago')
  or (team = 'Canada' and name = 'J. David')
  or (team = 'Canada' and name = 'P. David')
  or (team = 'Canada' and name = 'C. Larin')
  or (team = 'Canada' and name = 'T. Oluwaseyi')
  or (team = 'Cape Verde Islands' and name = 'Nuno da Costa')
  or (team = 'Cape Verde Islands' and name = 'Jovane Cabral')
  or (team = 'Cape Verde Islands' and name = 'Gilson Benchimol')
  or (team = 'Cape Verde Islands' and name = 'D. Livramento')
  or (team = 'Congo DR' and name = 'C. Bakambu')
  or (team = 'Congo DR' and name = 'S. Banza')
  or (team = 'Congo DR' and name = 'B. Cipenga')
  or (team = 'Congo DR' and name = 'M. Elia')
  or (team = 'Congo DR' and name = 'G. Kakuta')
  or (team = 'Congo DR' and name = 'F. Mayele')
  or (team = 'Congo DR' and name = 'Y. Wissa')
  or (team = 'Croatia' and name = 'M. Baturina')
  or (team = 'Croatia' and name = 'P. Sucic')
  or (team = 'Croatia' and name = 'A. Budimir')
  or (team = 'Croatia' and name = 'A. Kramaric')
  or (team = 'Croatia' and name = 'I. Matanovic')
  or (team = 'Croatia' and name = 'P. Musa')
  or (team = 'Croatia' and name = 'M. Pasalic')
  or (team = 'Ecuador' and name = 'K. Rodríguez')
  or (team = 'Ecuador' and name = 'J. Caicedo')
  or (team = 'Ecuador' and name = 'Jeremy Arévalo')
  or (team = 'Ecuador' and name = 'G. Plata')
  or (team = 'Ecuador' and name = 'E. Valencia')
  or (team = 'England' and name = 'A. Gordon')
  or (team = 'England' and name = 'N. Madueke')
  or (team = 'England' and name = 'M. Rashford')
  or (team = 'England' and name = 'I. Toney')
  or (team = 'England' and name = 'O. Watkins')
  or (team = 'Germany' and name = 'M. Neuer')
  or (team = 'Germany' and name = 'J. Leweling')
  or (team = 'Germany' and name = 'L. Sané')
  or (team = 'Germany' and name = 'K. Havertz')
  or (team = 'Germany' and name = 'M. Beier')
  or (team = 'Germany' and name = 'D. Undav')
  or (team = 'Germany' and name = 'N. Woltemade')
  or (team = 'Ghana' and name = 'A. Semenyo')
  or (team = 'Ghana' and name = 'B. Thomas-Asante')
  or (team = 'Ghana' and name = 'J. Ayew')
  or (team = 'Ghana' and name = 'C. Bonsu Baah')
  or (team = 'Ghana' and name = 'I. Williams')
  or (team = 'Ghana' and name = 'E. Nuamah')
  or (team = 'Ghana' and name = 'K. Sulemana')
  or (team = 'Haiti' and name = 'L. Deedson')
  or (team = 'Haiti' and name = 'D. Etienne')
  or (team = 'Haiti' and name = 'Y. Fortuné')
  or (team = 'Haiti' and name = 'W. Isidor')
  or (team = 'Haiti' and name = 'L. Joseph')
  or (team = 'Haiti' and name = 'D. Nazon')
  or (team = 'Haiti' and name = 'F. Pierrot')
  or (team = 'Iraq' and name = 'Youssef Amyn')
  or (team = 'Iraq' and name = 'A. Jasim')
  or (team = 'Iraq' and name = 'Ali Al Hamadi')
  or (team = 'Iraq' and name = 'Aymen Hussein')
  or (team = 'Iraq' and name = 'Meme')
  or (team = 'Iraq' and name = 'A. Qasem')
  or (team = 'Iraq' and name = 'A. Y. Hashim')
  or (team = 'Ivory Coast' and name = 'B. Touré')
  or (team = 'Ivory Coast' and name = 'S. Adingra')
  or (team = 'Ivory Coast' and name = 'A. Bonny')
  or (team = 'Ivory Coast' and name = 'A. Diallo')
  or (team = 'Ivory Coast' and name = 'E. Guessand')
  or (team = 'Ivory Coast' and name = 'N. Pépé')
  or (team = 'Ivory Coast' and name = 'E. Wahi')
  or (team = 'Japan' and name = 'J. Ito')
  or (team = 'Japan' and name = 'D. Maeda')
  or (team = 'Japan' and name = 'K. Goto')
  or (team = 'Japan' and name = 'Koki Ogawa')
  or (team = 'Japan' and name = 'K. Shiogai')
  or (team = 'Japan' and name = 'A. Ueda')
  or (team = 'Jordan' and name = 'Mohammed Abu Zurayq')
  or (team = 'Jordan' and name = 'O. Al Fakhouri')
  or (team = 'Jordan' and name = 'A. Azaizeh')
  or (team = 'Jordan' and name = 'Ali Olwan')
  or (team = 'Jordan' and name = 'Ibrahim Sabra')
  or (team = 'Jordan' and name = 'Mousa Tamari')
  or (team = 'Mexico' and name = 'S. Giménez')
  or (team = 'Mexico' and name = 'A. González')
  or (team = 'Mexico' and name = 'R. Jiménez')
  or (team = 'Mexico' and name = 'G. Martínez')
  or (team = 'Mexico' and name = 'A. Vega')
  or (team = 'Morocco' and name = 'I. Saibari')
  or (team = 'Morocco' and name = 'Gessime Yassine')
  or (team = 'Morocco' and name = 'A. El Kaabi')
  or (team = 'Morocco' and name = 'S. Rahimi')
  or (team = 'Netherlands' and name = 'J. Kluivert')
  or (team = 'Netherlands' and name = 'B. Brobbey')
  or (team = 'Netherlands' and name = 'M. Depay')
  or (team = 'Netherlands' and name = 'N. Lang')
  or (team = 'Netherlands' and name = 'D. Malen')
  or (team = 'Netherlands' and name = 'C. Summerville')
  or (team = 'Netherlands' and name = 'W. Weghorst')
  or (team = 'Norway' and name = 'A. Schjelderup')
  or (team = 'Norway' and name = 'J. Strand Larsen')
  or (team = 'Norway' and name = 'A. Sørloth')
  or (team = 'Panama' and name = 'A. Quintero')
  or (team = 'Panama' and name = 'C. Yanis')
  or (team = 'Panama' and name = 'J. Fajardo')
  or (team = 'Panama' and name = 'T. Rodríguez')
  or (team = 'Panama' and name = 'C. Waterman')
  or (team = 'Paraguay' and name = 'A. Romero')
  or (team = 'Paraguay' and name = 'A. Arce')
  or (team = 'Paraguay' and name = 'G. Ávalos')
  or (team = 'Paraguay' and name = 'J. Enciso')
  or (team = 'Paraguay' and name = 'I. Pitta')
  or (team = 'Paraguay' and name = 'A. Sanabria')
  or (team = 'Portugal' and name = 'Diogo Costa')
  or (team = 'Portugal' and name = 'Francisco Conceição')
  or (team = 'Portugal' and name = 'Gonçalo Guedes')
  or (team = 'Portugal' and name = 'João Félix')
  or (team = 'Portugal' and name = 'Trincão')
  or (team = 'Qatar' and name = 'Ahmed Al Ganehi')
  or (team = 'Qatar' and name = 'Hassan Al Haydos')
  or (team = 'Qatar' and name = 'Y. Abdurisag')
  or (team = 'Qatar' and name = 'Akram Afif')
  or (team = 'Qatar' and name = 'Ahmed Alaa')
  or (team = 'Qatar' and name = 'Almoez Ali')
  or (team = 'Qatar' and name = 'Edmilson Junior')
  or (team = 'Qatar' and name = 'Tahsin Jamshid')
  or (team = 'Qatar' and name = 'Mohammed Muntari')
  or (team = 'Saudi Arabia' and name = 'Musab Al Juwayr')
  or (team = 'Saudi Arabia' and name = 'Khalid Al Ghannam')
  or (team = 'Saudi Arabia' and name = 'Sultan Mandash')
  or (team = 'Saudi Arabia' and name = 'Ayman Yahya')
  or (team = 'Saudi Arabia' and name = 'Feras Al Brikan')
  or (team = 'Saudi Arabia' and name = 'Abdullah Al Hamdan')
  or (team = 'Saudi Arabia' and name = 'Saleh Al Shehri')
  or (team = 'Scotland' and name = 'C. Adams')
  or (team = 'Scotland' and name = 'L. Dykes')
  or (team = 'Scotland' and name = 'G. Hirst')
  or (team = 'Scotland' and name = 'L. Shankland')
  or (team = 'Scotland' and name = 'R. Stewart')
  or (team = 'South Africa' and name = 'O. Appollis')
  or (team = 'South Africa' and name = 'L. Foster')
  or (team = 'South Africa' and name = 'E. Makgopa')
  or (team = 'South Africa' and name = 'T. Maseko')
  or (team = 'South Africa' and name = 'R. Mofokeng')
  or (team = 'South Africa' and name = 'I. Rayners')
  or (team = 'South Korea' and name = 'Bae Jun-Ho')
  or (team = 'South Korea' and name = 'Eom Ji-Sung')
  or (team = 'South Korea' and name = 'Lee Dong-Gyeong')
  or (team = 'South Korea' and name = 'Yang Hyun-Jun')
  or (team = 'South Korea' and name = 'Hwang Hee-Chan')
  or (team = 'South Korea' and name = 'Cho Gue-Sung')
  or (team = 'South Korea' and name = 'Oh Hyeon-Gyu')
  or (team = 'Spain' and name = 'Unai Simón')
  or (team = 'Spain' and name = 'Borja Iglesias')
  or (team = 'Spain' and name = 'Víctor Muñoz')
  or (team = 'Spain' and name = 'Mikel Oyarzabal')
  or (team = 'Sweden' and name = 'B. Nygren')
  or (team = 'Sweden' and name = 'A. Elanga')
  or (team = 'Sweden' and name = 'V. Gyökeres')
  or (team = 'Sweden' and name = 'A. Isak')
  or (team = 'Sweden' and name = 'G. Nilsson')
  or (team = 'Switzerland' and name = 'C. Itten')
  or (team = 'Switzerland' and name = 'R. Vargas')
  or (team = 'Switzerland' and name = 'Z. Amdouni')
  or (team = 'Switzerland' and name = 'B. Embolo')
  or (team = 'Switzerland' and name = 'J. Manzambi')
  or (team = 'Switzerland' and name = 'N. Okafor')
  or (team = 'Tunisia' and name = 'K. Ayari')
  or (team = 'Tunisia' and name = 'S. Tounekti')
  or (team = 'Tunisia' and name = 'F. Chaouat')
  or (team = 'Tunisia' and name = 'R. Elloumi')
  or (team = 'Tunisia' and name = 'H. Mastouri')
  or (team = 'Tunisia' and name = 'E. Saad')
  or (team = 'Turkey' and name = 'K. Aktürkoglu')
  or (team = 'Turkey' and name = 'D. Gül')
  or (team = 'Turkey' and name = 'K. Yildiz')
  or (team = 'Turkey' and name = 'B. Yilmaz');

update public.fantasy_players set price = 5.5 where
  (team = 'England' and name = 'J. Pickford');

update public.fantasy_players set price = 6 where
  (team = 'Argentina' and name = 'E. Martínez')
  or (team = 'Mexico' and name = 'E. Álvarez');

update public.fantasy_players set price = 9 where
  (team = 'Argentina' and name = 'C. Romero')
  or (team = 'Canada' and name = 'A. Davies')
  or (team = 'Germany' and name = 'A. Rüdiger')
  or (team = 'Japan' and name = 'T. Kubo')
  or (team = 'Portugal' and name = 'Rúben Dias');

update public.fantasy_players set price = 9.5 where
  (team = 'Morocco' and name = 'A. Hakimi');

update public.fantasy_players set price = 10.5 where
  (team = 'Netherlands' and name = 'V. van Dijk')
  or (team = 'Portugal' and name = 'Pedro Neto')
  or (team = 'Portugal' and name = 'Gonçalo Ramos');

update public.fantasy_players set price = 11 where
  (team = 'Argentina' and name = 'E. Fernández')
  or (team = 'Argentina' and name = 'A. Mac Allister')
  or (team = 'Netherlands' and name = 'F. de Jong')
  or (team = 'South Korea' and name = 'Son Heung-Min');

update public.fantasy_players set price = 12 where
  (team = 'Spain' and name = 'Dani Olmo');

update public.fantasy_players set price = 13 where
  (team = 'England' and name = 'D. Rice')
  or (team = 'Netherlands' and name = 'C. Gakpo')
  or (team = 'Spain' and name = 'Gavi');

update public.fantasy_players set price = 14 where
  (team = 'Brazil' and name = 'Neymar')
  or (team = 'Portugal' and name = 'Bernardo Silva')
  or (team = 'Portugal' and name = 'Cristiano Ronaldo');

update public.fantasy_players set price = 15 where
  (team = 'Portugal' and name = 'Bruno Fernandes')
  or (team = 'Portugal' and name = 'Vitinha')
  or (team = 'Portugal' and name = 'Rafael Leão')
  or (team = 'Spain' and name = 'Nico Williams');

update public.fantasy_players set price = 16 where
  (team = 'Argentina' and name = 'J. Álvarez')
  or (team = 'Spain' and name = 'Pedri');

update public.fantasy_players set price = 17 where
  (team = 'England' and name = 'B. Saka')
  or (team = 'Germany' and name = 'J. Musiala')
  or (team = 'Germany' and name = 'F. Wirtz')
  or (team = 'Spain' and name = 'Rodri')
  or (team = 'Spain' and name = 'Lamine Yamal');

update public.fantasy_players set price = 18 where
  (team = 'Argentina' and name = 'Lisandro Martínez')
  or (team = 'Argentina' and name = 'Lautaro Martínez')
  or (team = 'Argentina' and name = 'L. Messi');

update public.fantasy_players set price = 19 where
  (team = 'England' and name = 'H. Kane');

update public.fantasy_players set price = 20 where
  (team = 'Brazil' and name = 'Vinícius Júnior')
  or (team = 'England' and name = 'J. Bellingham');

update public.fantasy_players set price = 21 where
  (team = 'Norway' and name = 'E. Haaland');

commit;

-- Control:  select price, count(*) from public.fantasy_players group by price order by price;
