-- =====================================================================
--  FANTASY · Poblar 12 equipos faltantes + corregir United States
--  Generado desde SquadLists-English.pdf (lista FIFA oficial 2026).
--  Seguro de correr: solo toca fantasy_players. Pegar en Supabase → SQL Editor.
--
--  1) Borra el plantel JUVENIL erróneo de USA (la API trajo el sub-20) y el
--     "Meme" de Iraq (no está en la convocatoria FIFA).
--  2) Inserta a mano los 12 equipos que faltaban + el plantel SENIOR de USA.
--     Foto = bandera del país (flagcdn). api_player_id queda NULL: estos
--     jugadores no tienen stats automáticas hasta cruzarlos con la API.
-- =====================================================================

begin;

-- 1) limpieza
delete from public.fantasy_players where team = 'United States';
delete from public.fantasy_players
 where team = 'Iraq' and name = 'Meme';

-- 2) alta (name, team, position, price, photo)
insert into public.fantasy_players (name, team, position, price, photo) values
  ('Thibaut Courtois', 'Belgium', 'GK', 6.5, 'https://flagcdn.com/w320/be.png'),
  ('Zeno Debast', 'Belgium', 'DEF', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Arthur Theate', 'Belgium', 'DEF', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Brandon Mechele', 'Belgium', 'DEF', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Maxim De Cuyper', 'Belgium', 'DEF', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Axel Witsel', 'Belgium', 'MID', 5, 'https://flagcdn.com/w320/be.png'),
  ('Kevin De Bruyne', 'Belgium', 'MID', 11, 'https://flagcdn.com/w320/be.png'),
  ('Youri Tielemans', 'Belgium', 'MID', 6.5, 'https://flagcdn.com/w320/be.png'),
  ('Romelu Lukaku', 'Belgium', 'FWD', 8.5, 'https://flagcdn.com/w320/be.png'),
  ('Leandro Trossard', 'Belgium', 'FWD', 7, 'https://flagcdn.com/w320/be.png'),
  ('Jeremy Doku', 'Belgium', 'FWD', 9.5, 'https://flagcdn.com/w320/be.png'),
  ('Senne Lammens', 'Belgium', 'GK', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Mike Penders', 'Belgium', 'GK', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Dodi Lukebakio', 'Belgium', 'FWD', 5.5, 'https://flagcdn.com/w320/be.png'),
  ('Thomas Meunier', 'Belgium', 'DEF', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Koni De Winter', 'Belgium', 'DEF', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Charles De Ketelaere', 'Belgium', 'FWD', 6.5, 'https://flagcdn.com/w320/be.png'),
  ('Joaquin Seys', 'Belgium', 'DEF', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Diego Moreira', 'Belgium', 'MID', 5, 'https://flagcdn.com/w320/be.png'),
  ('Hans Vanaken', 'Belgium', 'MID', 5, 'https://flagcdn.com/w320/be.png'),
  ('Timothy Castagne', 'Belgium', 'DEF', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Alexis Saelemaekers', 'Belgium', 'MID', 6, 'https://flagcdn.com/w320/be.png'),
  ('Nicolas Raskin', 'Belgium', 'MID', 5, 'https://flagcdn.com/w320/be.png'),
  ('Amadou Onana', 'Belgium', 'MID', 6.5, 'https://flagcdn.com/w320/be.png'),
  ('Nathan Ngoy', 'Belgium', 'DEF', 4.5, 'https://flagcdn.com/w320/be.png'),
  ('Matias Fernandez-Pardo', 'Belgium', 'FWD', 5.5, 'https://flagcdn.com/w320/be.png'),
  ('Nikola Vasilj', 'Bosnia-Herzegovina', 'GK', 4.5, 'https://flagcdn.com/w320/ba.png'),
  ('Nihad Mujakic', 'Bosnia-Herzegovina', 'DEF', 4.5, 'https://flagcdn.com/w320/ba.png'),
  ('Dennis Hadzikadunic', 'Bosnia-Herzegovina', 'DEF', 4.5, 'https://flagcdn.com/w320/ba.png'),
  ('Tarik Muharemovic', 'Bosnia-Herzegovina', 'DEF', 4.5, 'https://flagcdn.com/w320/ba.png'),
  ('Sead Kolasinac', 'Bosnia-Herzegovina', 'DEF', 6, 'https://flagcdn.com/w320/ba.png'),
  ('Benjamin Tahirovic', 'Bosnia-Herzegovina', 'MID', 5, 'https://flagcdn.com/w320/ba.png'),
  ('Amar Dedic', 'Bosnia-Herzegovina', 'DEF', 6, 'https://flagcdn.com/w320/ba.png'),
  ('Armin Gigovic', 'Bosnia-Herzegovina', 'MID', 5, 'https://flagcdn.com/w320/ba.png'),
  ('Samed Bazdar', 'Bosnia-Herzegovina', 'FWD', 5.5, 'https://flagcdn.com/w320/ba.png'),
  ('Ermedin Demirovic', 'Bosnia-Herzegovina', 'FWD', 6.5, 'https://flagcdn.com/w320/ba.png'),
  ('Edin Dzeko', 'Bosnia-Herzegovina', 'FWD', 7, 'https://flagcdn.com/w320/ba.png'),
  ('Mladen Jurkas', 'Bosnia-Herzegovina', 'GK', 4.5, 'https://flagcdn.com/w320/ba.png'),
  ('Ivan Basic', 'Bosnia-Herzegovina', 'MID', 5, 'https://flagcdn.com/w320/ba.png'),
  ('Ivan Sunjic', 'Bosnia-Herzegovina', 'MID', 5, 'https://flagcdn.com/w320/ba.png'),
  ('Amar Memic', 'Bosnia-Herzegovina', 'MID', 5, 'https://flagcdn.com/w320/ba.png'),
  ('Amir Hadziahmetovic', 'Bosnia-Herzegovina', 'MID', 5, 'https://flagcdn.com/w320/ba.png'),
  ('Dzenis Burnic', 'Bosnia-Herzegovina', 'MID', 5, 'https://flagcdn.com/w320/ba.png'),
  ('Nikola Katic', 'Bosnia-Herzegovina', 'DEF', 4.5, 'https://flagcdn.com/w320/ba.png'),
  ('Kerim Alajbegovic', 'Bosnia-Herzegovina', 'FWD', 5.5, 'https://flagcdn.com/w320/ba.png'),
  ('Esmir Bajraktarevic', 'Bosnia-Herzegovina', 'FWD', 5.5, 'https://flagcdn.com/w320/ba.png'),
  ('Stjepan Radeljic', 'Bosnia-Herzegovina', 'DEF', 4.5, 'https://flagcdn.com/w320/ba.png'),
  ('Martin Zlomislic', 'Bosnia-Herzegovina', 'GK', 4.5, 'https://flagcdn.com/w320/ba.png'),
  ('Haris Tabakovic', 'Bosnia-Herzegovina', 'FWD', 5.5, 'https://flagcdn.com/w320/ba.png'),
  ('Nidal Celik', 'Bosnia-Herzegovina', 'DEF', 4.5, 'https://flagcdn.com/w320/ba.png'),
  ('Jovo Lukic', 'Bosnia-Herzegovina', 'FWD', 5.5, 'https://flagcdn.com/w320/ba.png'),
  ('Ermin Mahmic', 'Bosnia-Herzegovina', 'MID', 5, 'https://flagcdn.com/w320/ba.png'),
  ('David Ospina', 'Colombia', 'GK', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Daniel Munoz', 'Colombia', 'DEF', 6.5, 'https://flagcdn.com/w320/co.png'),
  ('Jhon Lucumi', 'Colombia', 'DEF', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Santiago Arias', 'Colombia', 'DEF', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Kevin Castano', 'Colombia', 'MID', 5, 'https://flagcdn.com/w320/co.png'),
  ('Richard Rios', 'Colombia', 'MID', 7, 'https://flagcdn.com/w320/co.png'),
  ('Luis Diaz', 'Colombia', 'FWD', 10.5, 'https://flagcdn.com/w320/co.png'),
  ('Jorge Carrascal', 'Colombia', 'MID', 6, 'https://flagcdn.com/w320/co.png'),
  ('Jhon Cordoba', 'Colombia', 'FWD', 6.5, 'https://flagcdn.com/w320/co.png'),
  ('James Rodriguez', 'Colombia', 'MID', 8.5, 'https://flagcdn.com/w320/co.png'),
  ('Jhon Arias', 'Colombia', 'MID', 7, 'https://flagcdn.com/w320/co.png'),
  ('Camilo Vargas', 'Colombia', 'GK', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Yerry Mina', 'Colombia', 'DEF', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Gustavo Puerta', 'Colombia', 'DEF', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Juan Portilla', 'Colombia', 'MID', 5, 'https://flagcdn.com/w320/co.png'),
  ('Jefferson Lerma', 'Colombia', 'MID', 6, 'https://flagcdn.com/w320/co.png'),
  ('Johan Mojica', 'Colombia', 'DEF', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Willer Ditta', 'Colombia', 'DEF', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Cucho Hernandez', 'Colombia', 'FWD', 6, 'https://flagcdn.com/w320/co.png'),
  ('Juan Quintero', 'Colombia', 'MID', 6, 'https://flagcdn.com/w320/co.png'),
  ('Jaminton Campaz', 'Colombia', 'FWD', 5.5, 'https://flagcdn.com/w320/co.png'),
  ('Deiver MacHado', 'Colombia', 'DEF', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Davinson Sanchez', 'Colombia', 'DEF', 6.5, 'https://flagcdn.com/w320/co.png'),
  ('Alvaro Montero', 'Colombia', 'GK', 4.5, 'https://flagcdn.com/w320/co.png'),
  ('Luis Suarez', 'Colombia', 'FWD', 6.5, 'https://flagcdn.com/w320/co.png'),
  ('Andres Gomez', 'Colombia', 'FWD', 5.5, 'https://flagcdn.com/w320/co.png'),
  ('Eloy Room', 'Curaçao', 'GK', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Shurandy Sambo', 'Curaçao', 'DEF', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Jurien Gaari', 'Curaçao', 'DEF', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Roshon Van Eijma', 'Curaçao', 'DEF', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Sherel Floranus', 'Curaçao', 'DEF', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Godfried Roemeratoe', 'Curaçao', 'MID', 5, 'https://flagcdn.com/w320/cw.png'),
  ('Juninho Bacuna', 'Curaçao', 'MID', 5, 'https://flagcdn.com/w320/cw.png'),
  ('Livano Comenencia', 'Curaçao', 'MID', 5, 'https://flagcdn.com/w320/cw.png'),
  ('Juergen Locadia', 'Curaçao', 'FWD', 6, 'https://flagcdn.com/w320/cw.png'),
  ('Leandro Bacuna', 'Curaçao', 'MID', 5, 'https://flagcdn.com/w320/cw.png'),
  ('Jeremy Antonisse', 'Curaçao', 'FWD', 5.5, 'https://flagcdn.com/w320/cw.png'),
  ('Sontje Hansen', 'Curaçao', 'FWD', 5.5, 'https://flagcdn.com/w320/cw.png'),
  ('Tyrese Noslin', 'Curaçao', 'FWD', 5.5, 'https://flagcdn.com/w320/cw.png'),
  ('Kenji Gorre', 'Curaçao', 'FWD', 5.5, 'https://flagcdn.com/w320/cw.png'),
  ('Arjany Martha', 'Curaçao', 'MID', 5, 'https://flagcdn.com/w320/cw.png'),
  ('Jearl Margaritha', 'Curaçao', 'FWD', 5.5, 'https://flagcdn.com/w320/cw.png'),
  ('Brandley Kuwas', 'Curaçao', 'FWD', 5.5, 'https://flagcdn.com/w320/cw.png'),
  ('Armando Obispo', 'Curaçao', 'DEF', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Gervane Kastaneer', 'Curaçao', 'FWD', 5.5, 'https://flagcdn.com/w320/cw.png'),
  ('Joshua Brenet', 'Curaçao', 'DEF', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Tahith Chong', 'Curaçao', 'MID', 6, 'https://flagcdn.com/w320/cw.png'),
  ('Kevin Felida', 'Curaçao', 'MID', 5, 'https://flagcdn.com/w320/cw.png'),
  ('Riechedly Bazoer', 'Curaçao', 'DEF', 5.5, 'https://flagcdn.com/w320/cw.png'),
  ('Deveron Fonville', 'Curaçao', 'DEF', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Tyrick Bodak', 'Curaçao', 'GK', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Trevor Doornbusch', 'Curaçao', 'GK', 4.5, 'https://flagcdn.com/w320/cw.png'),
  ('Matej Kovar', 'Czechia', 'GK', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('David Zima', 'Czechia', 'DEF', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Tomas Holes', 'Czechia', 'DEF', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Robin Hranac', 'Czechia', 'DEF', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Vladimir Coufal', 'Czechia', 'DEF', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Stepan Chaloupek', 'Czechia', 'DEF', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Ladislav Krejci', 'Czechia', 'DEF', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Vladimir Darida', 'Czechia', 'MID', 5, 'https://flagcdn.com/w320/cz.png'),
  ('Adam Hlozek', 'Czechia', 'FWD', 7, 'https://flagcdn.com/w320/cz.png'),
  ('Patrik Schick', 'Czechia', 'FWD', 8.5, 'https://flagcdn.com/w320/cz.png'),
  ('Jan Kuchta', 'Czechia', 'FWD', 5.5, 'https://flagcdn.com/w320/cz.png'),
  ('Lukas Cerv', 'Czechia', 'MID', 5, 'https://flagcdn.com/w320/cz.png'),
  ('Mojmir Chytil', 'Czechia', 'FWD', 5.5, 'https://flagcdn.com/w320/cz.png'),
  ('David Jurasek', 'Czechia', 'DEF', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Pavel Sulc', 'Czechia', 'FWD', 5.5, 'https://flagcdn.com/w320/cz.png'),
  ('Jindrich Stanek', 'Czechia', 'GK', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Lukas Provod', 'Czechia', 'MID', 6, 'https://flagcdn.com/w320/cz.png'),
  ('Michal Sadilek', 'Czechia', 'MID', 5, 'https://flagcdn.com/w320/cz.png'),
  ('Tomas Chory', 'Czechia', 'FWD', 5.5, 'https://flagcdn.com/w320/cz.png'),
  ('Jaroslav Zeleny', 'Czechia', 'DEF', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('David Doudera', 'Czechia', 'DEF', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Tomas Soucek', 'Czechia', 'MID', 7.5, 'https://flagcdn.com/w320/cz.png'),
  ('Lukas Hornicek', 'Czechia', 'GK', 4.5, 'https://flagcdn.com/w320/cz.png'),
  ('Alexandr Sojka', 'Czechia', 'MID', 5, 'https://flagcdn.com/w320/cz.png'),
  ('Hugo Sochurek', 'Czechia', 'MID', 5, 'https://flagcdn.com/w320/cz.png'),
  ('Denis Visinsky', 'Czechia', 'FWD', 5.5, 'https://flagcdn.com/w320/cz.png'),
  ('Mohamed Elshenawy', 'Egypt', 'GK', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Yasser Ibrahim', 'Egypt', 'DEF', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mohamed Hany', 'Egypt', 'DEF', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Hossam Abdelmaguid', 'Egypt', 'DEF', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Ramy Rabia', 'Egypt', 'DEF', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mohamed Abdelmoneim', 'Egypt', 'DEF', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mahmoud Trezeguet', 'Egypt', 'FWD', 6.5, 'https://flagcdn.com/w320/eg.png'),
  ('Emam Ashour', 'Egypt', 'MID', 6, 'https://flagcdn.com/w320/eg.png'),
  ('Hamza Abdelkarim', 'Egypt', 'FWD', 5.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mohamed Salah', 'Egypt', 'FWD', 12.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mostafa Zico', 'Egypt', 'MID', 5, 'https://flagcdn.com/w320/eg.png'),
  ('Haissem Hassan', 'Egypt', 'FWD', 5.5, 'https://flagcdn.com/w320/eg.png'),
  ('Ahmed Fatouh', 'Egypt', 'DEF', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Hamdy Fathy', 'Egypt', 'MID', 5, 'https://flagcdn.com/w320/eg.png'),
  ('Karim Hafez', 'Egypt', 'DEF', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mahdy Soliman', 'Egypt', 'GK', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mohanad Lashin', 'Egypt', 'MID', 5, 'https://flagcdn.com/w320/eg.png'),
  ('Nabil Donga', 'Egypt', 'MID', 5, 'https://flagcdn.com/w320/eg.png'),
  ('Marawan Attia', 'Egypt', 'MID', 5, 'https://flagcdn.com/w320/eg.png'),
  ('Ibrahim Adel', 'Egypt', 'FWD', 5.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mahmoud Saber', 'Egypt', 'MID', 5, 'https://flagcdn.com/w320/eg.png'),
  ('Omar Marmoush', 'Egypt', 'FWD', 9.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mostafa Shoubir', 'Egypt', 'GK', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Tarek Alaa', 'Egypt', 'DEF', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Ahmed Zizo', 'Egypt', 'FWD', 5.5, 'https://flagcdn.com/w320/eg.png'),
  ('Mohamed Alaa', 'Egypt', 'GK', 4.5, 'https://flagcdn.com/w320/eg.png'),
  ('Brice Samba', 'France', 'GK', 4.5, 'https://flagcdn.com/w320/fr.png'),
  ('Malo Gusto', 'France', 'DEF', 5.5, 'https://flagcdn.com/w320/fr.png'),
  ('Lucas Digne', 'France', 'DEF', 4.5, 'https://flagcdn.com/w320/fr.png'),
  ('Dayot Upamecano', 'France', 'DEF', 7.5, 'https://flagcdn.com/w320/fr.png'),
  ('Jules Kounde', 'France', 'DEF', 7.5, 'https://flagcdn.com/w320/fr.png'),
  ('Manu Kone', 'France', 'MID', 6, 'https://flagcdn.com/w320/fr.png'),
  ('Ousmane Dembele', 'France', 'FWD', 11.5, 'https://flagcdn.com/w320/fr.png'),
  ('Aurelien Tchouameni', 'France', 'MID', 10.5, 'https://flagcdn.com/w320/fr.png'),
  ('Marcus Thuram', 'France', 'FWD', 9, 'https://flagcdn.com/w320/fr.png'),
  ('Kylian Mbappe', 'France', 'FWD', 15, 'https://flagcdn.com/w320/fr.png'),
  ('Michael Olise', 'France', 'FWD', 9.5, 'https://flagcdn.com/w320/fr.png'),
  ('Bradley Barcola', 'France', 'FWD', 10, 'https://flagcdn.com/w320/fr.png'),
  ('Ngolo Kante', 'France', 'MID', 7, 'https://flagcdn.com/w320/fr.png'),
  ('Adrien Rabiot', 'France', 'MID', 7, 'https://flagcdn.com/w320/fr.png'),
  ('Ibrahima Konate', 'France', 'DEF', 7.5, 'https://flagcdn.com/w320/fr.png'),
  ('Mike Maignan', 'France', 'GK', 6, 'https://flagcdn.com/w320/fr.png'),
  ('William Saliba', 'France', 'DEF', 9, 'https://flagcdn.com/w320/fr.png'),
  ('Warren Zaire-Emery', 'France', 'MID', 6.5, 'https://flagcdn.com/w320/fr.png'),
  ('Theo Hernandez', 'France', 'DEF', 8.5, 'https://flagcdn.com/w320/fr.png'),
  ('Desire Doue', 'France', 'FWD', 8, 'https://flagcdn.com/w320/fr.png'),
  ('Lucas Hernandez', 'France', 'DEF', 6, 'https://flagcdn.com/w320/fr.png'),
  ('Jean-Philippe Mateta', 'France', 'FWD', 6.5, 'https://flagcdn.com/w320/fr.png'),
  ('Robin Risser', 'France', 'GK', 4.5, 'https://flagcdn.com/w320/fr.png'),
  ('Rayan Cherki', 'France', 'MID', 7, 'https://flagcdn.com/w320/fr.png'),
  ('Maghnes Akliouche', 'France', 'MID', 5, 'https://flagcdn.com/w320/fr.png'),
  ('Maxence Lacroix', 'France', 'DEF', 4.5, 'https://flagcdn.com/w320/fr.png'),
  ('Alireza Beiranvand', 'Iran', 'GK', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Saleh Hardani', 'Iran', 'DEF', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Ehsan Hajisafi', 'Iran', 'DEF', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Shoja Khalilzadeh', 'Iran', 'DEF', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Milad Mohammadi', 'Iran', 'DEF', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Saeid Ezatolahi', 'Iran', 'MID', 5, 'https://flagcdn.com/w320/ir.png'),
  ('Alireza Jahanbakhsh', 'Iran', 'MID', 6.5, 'https://flagcdn.com/w320/ir.png'),
  ('Mohammad Mohebbi', 'Iran', 'MID', 5, 'https://flagcdn.com/w320/ir.png'),
  ('Mehdi Taremi', 'Iran', 'FWD', 8, 'https://flagcdn.com/w320/ir.png'),
  ('Mehdi Ghayedi', 'Iran', 'FWD', 5.5, 'https://flagcdn.com/w320/ir.png'),
  ('Ali Alipour', 'Iran', 'FWD', 5.5, 'https://flagcdn.com/w320/ir.png'),
  ('Payam Niazmand', 'Iran', 'GK', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Hossein Kanani', 'Iran', 'DEF', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Saman Ghoddos', 'Iran', 'MID', 6, 'https://flagcdn.com/w320/ir.png'),
  ('Roozbeh Cheshmi', 'Iran', 'MID', 5, 'https://flagcdn.com/w320/ir.png'),
  ('Mehdi Torabi', 'Iran', 'MID', 5, 'https://flagcdn.com/w320/ir.png'),
  ('Arya Yousefi', 'Iran', 'DEF', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Amirhossein Hosseinzadeh', 'Iran', 'FWD', 5.5, 'https://flagcdn.com/w320/ir.png'),
  ('Ali Nemati', 'Iran', 'DEF', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Shahriyar Moghanloo', 'Iran', 'FWD', 5.5, 'https://flagcdn.com/w320/ir.png'),
  ('Mohammad Ghorbani', 'Iran', 'MID', 5, 'https://flagcdn.com/w320/ir.png'),
  ('Hossein Hosseini', 'Iran', 'GK', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Ramin Rezaeian', 'Iran', 'DEF', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Dennis Dargahi', 'Iran', 'FWD', 5.5, 'https://flagcdn.com/w320/ir.png'),
  ('Danial Iri', 'Iran', 'DEF', 4.5, 'https://flagcdn.com/w320/ir.png'),
  ('Amirmohammad Razaghinia', 'Iran', 'MID', 5, 'https://flagcdn.com/w320/ir.png'),
  ('Max Crocombe', 'New Zealand', 'GK', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Tim Payne', 'New Zealand', 'DEF', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Francis De Vries', 'New Zealand', 'DEF', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Tyler Bindon', 'New Zealand', 'DEF', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Michael Boxall', 'New Zealand', 'DEF', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Joe Bell', 'New Zealand', 'MID', 5, 'https://flagcdn.com/w320/nz.png'),
  ('Matthew Garbett', 'New Zealand', 'MID', 5, 'https://flagcdn.com/w320/nz.png'),
  ('Marko Stamenic', 'New Zealand', 'MID', 5.5, 'https://flagcdn.com/w320/nz.png'),
  ('Chris Wood', 'New Zealand', 'FWD', 7, 'https://flagcdn.com/w320/nz.png'),
  ('Sarpreet Singh', 'New Zealand', 'MID', 5, 'https://flagcdn.com/w320/nz.png'),
  ('Elijah Just', 'New Zealand', 'MID', 5, 'https://flagcdn.com/w320/nz.png'),
  ('Alex Paulsen', 'New Zealand', 'GK', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Liberato Cacace', 'New Zealand', 'DEF', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Alex Rufer', 'New Zealand', 'MID', 5, 'https://flagcdn.com/w320/nz.png'),
  ('Nando Pijnaker', 'New Zealand', 'DEF', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Finn Surman', 'New Zealand', 'DEF', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Kosta Barbarouses', 'New Zealand', 'FWD', 5.5, 'https://flagcdn.com/w320/nz.png'),
  ('Ben Benjamin Waine', 'New Zealand', 'FWD', 5.5, 'https://flagcdn.com/w320/nz.png'),
  ('Ben Benjamin Old', 'New Zealand', 'MID', 5, 'https://flagcdn.com/w320/nz.png'),
  ('Callum McCowatt', 'New Zealand', 'MID', 5, 'https://flagcdn.com/w320/nz.png'),
  ('Jesse Randall', 'New Zealand', 'FWD', 5.5, 'https://flagcdn.com/w320/nz.png'),
  ('Michael Woud', 'New Zealand', 'GK', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Ryan Thomas', 'New Zealand', 'MID', 5, 'https://flagcdn.com/w320/nz.png'),
  ('Callan Elliot', 'New Zealand', 'DEF', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Lachlan Bayliss', 'New Zealand', 'MID', 5, 'https://flagcdn.com/w320/nz.png'),
  ('Tommy Smith', 'New Zealand', 'DEF', 4.5, 'https://flagcdn.com/w320/nz.png'),
  ('Yehvann Diouf', 'Senegal', 'GK', 4.5, 'https://flagcdn.com/w320/sn.png'),
  ('Mamadou Sarr', 'Senegal', 'DEF', 4.5, 'https://flagcdn.com/w320/sn.png'),
  ('Kalidou Koulibaly', 'Senegal', 'DEF', 7, 'https://flagcdn.com/w320/sn.png'),
  ('Abdoulaye Seck', 'Senegal', 'DEF', 4.5, 'https://flagcdn.com/w320/sn.png'),
  ('Idrissa Gueye', 'Senegal', 'MID', 6, 'https://flagcdn.com/w320/sn.png'),
  ('Pathe Ciss', 'Senegal', 'MID', 5, 'https://flagcdn.com/w320/sn.png'),
  ('Assane Diao', 'Senegal', 'FWD', 6, 'https://flagcdn.com/w320/sn.png'),
  ('Lamine Camara', 'Senegal', 'MID', 6, 'https://flagcdn.com/w320/sn.png'),
  ('Bamba Dieng', 'Senegal', 'FWD', 5.5, 'https://flagcdn.com/w320/sn.png'),
  ('Sadio Mane', 'Senegal', 'FWD', 8.5, 'https://flagcdn.com/w320/sn.png'),
  ('Nicolas Jackson', 'Senegal', 'FWD', 9, 'https://flagcdn.com/w320/sn.png'),
  ('Cherif Ndiaye', 'Senegal', 'FWD', 5.5, 'https://flagcdn.com/w320/sn.png'),
  ('Iliman Ndiaye', 'Senegal', 'FWD', 7.5, 'https://flagcdn.com/w320/sn.png'),
  ('Ismail Jakobs', 'Senegal', 'DEF', 4.5, 'https://flagcdn.com/w320/sn.png'),
  ('Krepin Diatta', 'Senegal', 'DEF', 4.5, 'https://flagcdn.com/w320/sn.png'),
  ('Edouard Mendy', 'Senegal', 'GK', 6, 'https://flagcdn.com/w320/sn.png'),
  ('Pape Sarr', 'Senegal', 'MID', 7, 'https://flagcdn.com/w320/sn.png'),
  ('Ismaila Sarr', 'Senegal', 'FWD', 8, 'https://flagcdn.com/w320/sn.png'),
  ('Moussa Niakhate', 'Senegal', 'DEF', 4.5, 'https://flagcdn.com/w320/sn.png'),
  ('Ibrahim Mbaye', 'Senegal', 'FWD', 5.5, 'https://flagcdn.com/w320/sn.png'),
  ('Habib Diarra', 'Senegal', 'MID', 6, 'https://flagcdn.com/w320/sn.png'),
  ('Bara Ndiaye', 'Senegal', 'MID', 5, 'https://flagcdn.com/w320/sn.png'),
  ('Mory Diaw', 'Senegal', 'GK', 4.5, 'https://flagcdn.com/w320/sn.png'),
  ('Antoine Mendy', 'Senegal', 'DEF', 4.5, 'https://flagcdn.com/w320/sn.png'),
  ('El Hadji Diouf', 'Senegal', 'DEF', 4.5, 'https://flagcdn.com/w320/sn.png'),
  ('Pape Gueye', 'Senegal', 'MID', 5, 'https://flagcdn.com/w320/sn.png'),
  ('Sergio Rochet', 'Uruguay', 'GK', 4.5, 'https://flagcdn.com/w320/uy.png'),
  ('Jose Gimenez', 'Uruguay', 'DEF', 6.5, 'https://flagcdn.com/w320/uy.png'),
  ('Sebastian Caceres', 'Uruguay', 'DEF', 4.5, 'https://flagcdn.com/w320/uy.png'),
  ('Ronald Araujo', 'Uruguay', 'DEF', 8, 'https://flagcdn.com/w320/uy.png'),
  ('Manuel Ugarte', 'Uruguay', 'MID', 6.5, 'https://flagcdn.com/w320/uy.png'),
  ('Rodrigo Bentancur', 'Uruguay', 'MID', 7, 'https://flagcdn.com/w320/uy.png'),
  ('Nicolas De La Cruz', 'Uruguay', 'MID', 6.5, 'https://flagcdn.com/w320/uy.png'),
  ('Federico Valverde', 'Uruguay', 'MID', 12, 'https://flagcdn.com/w320/uy.png'),
  ('Darwin Nunez', 'Uruguay', 'FWD', 9.5, 'https://flagcdn.com/w320/uy.png'),
  ('Giorgian De Arrascaeta', 'Uruguay', 'MID', 7, 'https://flagcdn.com/w320/uy.png'),
  ('Facundo Pellistri', 'Uruguay', 'FWD', 5.5, 'https://flagcdn.com/w320/uy.png'),
  ('Santiago Mele', 'Uruguay', 'GK', 4.5, 'https://flagcdn.com/w320/uy.png'),
  ('Guillermo Varela', 'Uruguay', 'DEF', 4.5, 'https://flagcdn.com/w320/uy.png'),
  ('Agustin Canobbio', 'Uruguay', 'MID', 5, 'https://flagcdn.com/w320/uy.png'),
  ('Emiliano Martinez', 'Uruguay', 'MID', 6.5, 'https://flagcdn.com/w320/uy.png'),
  ('Mathias Olivera', 'Uruguay', 'DEF', 4.5, 'https://flagcdn.com/w320/uy.png'),
  ('Matias Vina', 'Uruguay', 'DEF', 4.5, 'https://flagcdn.com/w320/uy.png'),
  ('Brian Rodriguez', 'Uruguay', 'FWD', 5.5, 'https://flagcdn.com/w320/uy.png'),
  ('Rodrigo Aguirre', 'Uruguay', 'FWD', 5.5, 'https://flagcdn.com/w320/uy.png'),
  ('Maxi Araujo', 'Uruguay', 'MID', 5, 'https://flagcdn.com/w320/uy.png'),
  ('Federico Vinas', 'Uruguay', 'FWD', 5.5, 'https://flagcdn.com/w320/uy.png'),
  ('Joaquin Piquerez', 'Uruguay', 'MID', 5, 'https://flagcdn.com/w320/uy.png'),
  ('Fernando Muslera', 'Uruguay', 'GK', 4.5, 'https://flagcdn.com/w320/uy.png'),
  ('Santiago Bueno', 'Uruguay', 'DEF', 4.5, 'https://flagcdn.com/w320/uy.png'),
  ('Juan Sanabria', 'Uruguay', 'MID', 5, 'https://flagcdn.com/w320/uy.png'),
  ('Rodrigo Zalazar', 'Uruguay', 'MID', 5, 'https://flagcdn.com/w320/uy.png'),
  ('Utkir Yusupov', 'Uzbekistan', 'GK', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Abdukodir Khusanov', 'Uzbekistan', 'DEF', 7, 'https://flagcdn.com/w320/uz.png'),
  ('Khojiakbar Alijonov', 'Uzbekistan', 'DEF', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Farrukh Sayfiev', 'Uzbekistan', 'DEF', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Rustam Ashurmatov', 'Uzbekistan', 'DEF', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Akmal Mozgovoy', 'Uzbekistan', 'MID', 5, 'https://flagcdn.com/w320/uz.png'),
  ('Otabek Shukurov', 'Uzbekistan', 'MID', 5, 'https://flagcdn.com/w320/uz.png'),
  ('Jamshid Iskanderov', 'Uzbekistan', 'MID', 5, 'https://flagcdn.com/w320/uz.png'),
  ('Odiljon Xamrobekov', 'Uzbekistan', 'MID', 5, 'https://flagcdn.com/w320/uz.png'),
  ('Jaloliddin Masharipov', 'Uzbekistan', 'MID', 5, 'https://flagcdn.com/w320/uz.png'),
  ('Oston Urunov', 'Uzbekistan', 'MID', 5, 'https://flagcdn.com/w320/uz.png'),
  ('Abduvohid Nematov', 'Uzbekistan', 'GK', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Sherzod Nasrullaev', 'Uzbekistan', 'DEF', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Eldor Shomurodov', 'Uzbekistan', 'FWD', 6.5, 'https://flagcdn.com/w320/uz.png'),
  ('Umar Eshmurodov', 'Uzbekistan', 'DEF', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Botirali Ergashev', 'Uzbekistan', 'GK', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Dostonbek Khamdamov', 'Uzbekistan', 'MID', 5, 'https://flagcdn.com/w320/uz.png'),
  ('Abdulla Abdullaev', 'Uzbekistan', 'DEF', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Azizjon Ganiev', 'Uzbekistan', 'MID', 5, 'https://flagcdn.com/w320/uz.png'),
  ('Azizbek Amonov', 'Uzbekistan', 'FWD', 5.5, 'https://flagcdn.com/w320/uz.png'),
  ('Igor Sergeev', 'Uzbekistan', 'FWD', 5.5, 'https://flagcdn.com/w320/uz.png'),
  ('Abbosbek Fayzullaev', 'Uzbekistan', 'MID', 6, 'https://flagcdn.com/w320/uz.png'),
  ('Sherzod Esanov', 'Uzbekistan', 'MID', 5, 'https://flagcdn.com/w320/uz.png'),
  ('Behruzjon Karimov', 'Uzbekistan', 'DEF', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Avazbek Ulmasaliyev', 'Uzbekistan', 'DEF', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Jakhongir Urozov', 'Uzbekistan', 'DEF', 4.5, 'https://flagcdn.com/w320/uz.png'),
  ('Matt Turner', 'United States', 'GK', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Sergino Dest', 'United States', 'DEF', 6, 'https://flagcdn.com/w320/us.png'),
  ('Chris Richards', 'United States', 'DEF', 6, 'https://flagcdn.com/w320/us.png'),
  ('Tyler Adams', 'United States', 'MID', 7, 'https://flagcdn.com/w320/us.png'),
  ('Antonee Robinson', 'United States', 'DEF', 6.5, 'https://flagcdn.com/w320/us.png'),
  ('Auston Trusty', 'United States', 'DEF', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Giovanni Reyna', 'United States', 'MID', 7, 'https://flagcdn.com/w320/us.png'),
  ('Weston McKennie', 'United States', 'MID', 7, 'https://flagcdn.com/w320/us.png'),
  ('Ricardo Pepi', 'United States', 'FWD', 6.5, 'https://flagcdn.com/w320/us.png'),
  ('Christian Pulisic', 'United States', 'FWD', 9, 'https://flagcdn.com/w320/us.png'),
  ('Brenden Aaronson', 'United States', 'FWD', 5.5, 'https://flagcdn.com/w320/us.png'),
  ('Miles Robinson', 'United States', 'DEF', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Tim Ream', 'United States', 'DEF', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Sebastian Berhalter', 'United States', 'MID', 5, 'https://flagcdn.com/w320/us.png'),
  ('Cristian Roldan', 'United States', 'MID', 5, 'https://flagcdn.com/w320/us.png'),
  ('Alex Freeman', 'United States', 'DEF', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Malik Tillman', 'United States', 'MID', 6.5, 'https://flagcdn.com/w320/us.png'),
  ('Max Arfsten', 'United States', 'DEF', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Haji Wright', 'United States', 'FWD', 5.5, 'https://flagcdn.com/w320/us.png'),
  ('Folarin Balogun', 'United States', 'FWD', 8, 'https://flagcdn.com/w320/us.png'),
  ('Timothy Weah', 'United States', 'FWD', 7, 'https://flagcdn.com/w320/us.png'),
  ('Mark McKenzie', 'United States', 'DEF', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Joe Scally', 'United States', 'DEF', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Matt Freese', 'United States', 'GK', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Chris Brady', 'United States', 'GK', 4.5, 'https://flagcdn.com/w320/us.png'),
  ('Alex Zendejas', 'United States', 'FWD', 5.5, 'https://flagcdn.com/w320/us.png');

commit;

-- Control rápido:
--   select team, count(*) from public.fantasy_players group by team order by team;
